name: pre-compile-ops-nv

on:
  push:
    branches:
      - 'staging**'
  pull_request:
    branches:
      '**'
  schedule:
    - cron: "0 0 * * *"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-ops:
    runs-on: ubuntu-20.04
    container:
      image: nvidia/cuda:11.7.1-devel-ubuntu20.04

    steps:
        - uses: actions/checkout@v2

        - name: environment
          run: |
            which python
            python --version
        - name: Compile DeepSpeed Ops
          run: |
            DS_BUILD_OPS=1 DS_BUILD_SPARSE_ATTN=0 pip3 install .
        - name: DS Report
          run: |
             ds_report
