name: nv-pre-compile-ops

on:
  push:
    branches:
      - 'staging**'
  pull_request:
    branches:
      '**'
  schedule:
    - cron: "0 0 * * *"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-ops:
    runs-on: ubuntu-20.04
    container:
      image: deepspeed/gh-builder:py310-torch112-cu116

    steps:
        - uses: actions/checkout@v2

        - name: environment
          run: |
            which python
            python --version
            python -c "import torch; print('torch:', torch.__version__, torch)"
            python -c "import torch; print('CUDA available:', torch.cuda.is_available())"
        - name: Compile DeepSpeed Ops
          run: |
            DS_BUILD_OPS=1 DS_BUILD_SPARSE_ATTN=0 pip3 install .
        - name: DS Report
          run: |
             ds_report
